trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 'ui/*'  # Trigger pipeline when anything under 'ui/' changes
      - 'users/*'  # Trigger pipeline when anything under 'users/' changes
      - 'posts/*'  # Trigger pipeline when anything under 'posts/' changes

pool:
  vmImage: ubuntu-latest

jobs:
  - job: BuildUI
    displayName: 'Build UI Service'
    condition: |
      and(
        eq(variables['Build.SourceBranchName'], 'main'),
        contains(variables['Build.ChangedFiles'], 'ui/')
      )
    steps:
      - template: template-pipeline.yml
        parameters:
          microservice: 'ui'  # The name of the microservice
          dockerfilePath: 'ui/Dockerfile'  # Path to the Dockerfile for UI service
          azureSubscription: 'test-aks-application12'  # The Azure subscription name
          imageName: '$(Build.Repository.Name)-$(Build.SourceBranchName)-ui:$(Build.BuildId)'  # The image name based on repo and branch

  - job: BuildUsers
    displayName: 'Build Users Service'
    condition: |
      and(
        eq(variables['Build.SourceBranchName'], 'main'),
        contains(variables['Build.ChangedFiles'], 'users/')
      )
    steps:
      - template: template-pipeline.yml
        parameters:
          microservice: 'users'  # The name of the microservice
          dockerfilePath: 'users/Dockerfile'  # Path to the Dockerfile for Users service
          azureSubscription: 'test-aks-application12'  # The Azure subscription name
          imageName: '$(Build.Repository.Name)-$(Build.SourceBranchName)-users:$(Build.BuildId)'  # The image name based on repo and branch

  - job: BuildPosts
    displayName: 'Build Posts Service'
    condition: |
      and(
        eq(variables['Build.SourceBranchName'], 'main'),
        contains(variables['Build.ChangedFiles'], 'posts/')
      )
    steps:
      - template: template-pipeline.yml
        parameters:
          microservice: 'posts'  # The name of the microservice
          dockerfilePath: 'posts/Dockerfile'  # Path to the Dockerfile for Posts service
          azureSubscription: 'test-aks-application12'  # The Azure subscription name
          imageName: '$(Build.Repository.Name)-$(Build.SourceBranchName)-posts:$(Build.BuildId)'  # The image name based on repo and branch
