trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 'ui/*'  # Trigger pipeline when anything under 'ui/' changes
      - 'users/*'  # Trigger pipeline when anything under 'users/' changes
      - 'posts/*'  # Trigger pipeline when anything under 'posts/' changes
      - 'comments/*'  # Trigger pipeline when anything under 'comments/' changes

pool:
  vmImage: ubuntu-latest

variables:
  serviceToBuild: ''

jobs:
  - job: DetermineService
    displayName: 'Determine Service to Build'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - checkout: self
        fetchDepth: 0  # Fetch all history to avoid shallow clone issues

      - script: |
          if [ $(git rev-list --count HEAD) -eq 1 ]; then
              echo "This is the first commit. No previous commit to compare."
              echo "##vso[task.setvariable variable=serviceToBuild]none"
          else
              changed_service=$(git diff --name-only HEAD^ HEAD | grep -E '^(ui|users|posts|comments)/' | cut -d'/' -f1 | uniq | head -n 1)
              if [ -z "$changed_service" ]; then
                  echo "No relevant changes detected."
                  echo "##vso[task.setvariable variable=serviceToBuild]none"
              else
                  echo "Detected changes in: $changed_service"
                  echo "##vso[task.setvariable variable=serviceToBuild]$changed_service"
              fi
          fi
        displayName: 'Determine Changed Service'

  - job: BuildComments
    displayName: 'Build Comments Service'
    condition: and(succeeded(), eq(variables['serviceToBuild'], 'comments'))
    steps:
      - script: |
          echo "Service to build: $(serviceToBuild)"
        displayName: 'Debug Service to Build'
      - template: template-pipeline.yml
        parameters:
          microservice: 'comments'
          dockerfilePath: 'comments/Dockerfile'
          azureSubscription: 'test-aks-application12'
          imageName: '$(Build.Repository.Name)-$(Build.SourceBranchName)-comments:$(Build.BuildId)'

