trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 'ui/*'
      - 'users/*'
      - 'posts/*'
      - 'comments/*'

pool:
  vmImage: ubuntu-latest

variables:
  serviceToBuild: ''

jobs:
  - job: DetermineService
    displayName: 'Determine Service to Build'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - checkout: self
        fetchDepth: 0  # Fetch all history to avoid shallow clone issues

      - script: |
          echo "Checking for changes..."
          if [ $(git rev-list --count HEAD) -eq 1 ]; then
              echo "This is the first commit. No previous commit to compare."
              echo "##vso[task.setvariable variable=serviceToBuild;]none"
          else
              changed_files=$(git diff --name-only HEAD~1 HEAD)
              echo "Changed files: $changed_files"
              # Ensure the paths are matching the correct service directories
              changed_service=$(echo "$changed_files" | grep -E '^(ui|users|posts|comments)/' | cut -d'/' -f1 | uniq | head -n 1)
              if [ -z "$changed_service" ]; then
                  echo "No relevant changes detected."
                  echo "##vso[task.setvariable variable=serviceToBuild;]none"
              else
                  echo "Detected changes in: $changed_service"
                  serviceToBuildTrimmed=$(echo "$changed_service" | xargs)
                  echo "##vso[task.setvariable variable=serviceToBuild;]$serviceToBuildTrimmed"
                  echo "##vso[task.setvariable variable=serviceToBuild;isOutput=true;]$serviceToBuildTrimmed"
              fi
          fi
        displayName: 'Determine Changed Service'

      - script: |
          echo "Service to build set to: $(serviceToBuild)"
          echo "Current build ID: $(Build.BuildId)"
          echo "Current repository: $(Build.Repository.Name)"
          echo "Current branch: $(Build.SourceBranchName)"
        displayName: 'Debug Service to Build'

    # Job output variables
    outputs:
      serviceToBuildOutput: $(serviceToBuild)

  - job: BuildComments
    displayName: 'Build Comments Service'
    dependsOn: DetermineService
    condition: and(succeeded(), eq(dependencies.DetermineService.outputs['DetermineService.serviceToBuildOutput'], 'comments'))
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: |
          echo "Service to build in BuildComments: $(serviceToBuild)"
        displayName: 'Debug Service to Build Comments'
      - template: template-pipeline.yml
        parameters:
          microservice: 'comments'
          dockerfilePath: 'comments/Dockerfile'
          azureSubscription: 'test-aks-application12'
          imageName: '$(Build.Repository.Name)-$(Build.SourceBranchName)-comments:$(Build.BuildId)'

  - job: BuildPosts
    displayName: 'Build Posts Service'
    dependsOn: DetermineService
    condition: and(succeeded(), eq(dependencies.DetermineService.outputs['DetermineService.serviceToBuildOutput'], 'posts'))
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: |
          echo "Service to build in BuildPosts: $(serviceToBuild)"
        displayName: 'Debug Service to Build Posts'
      - template: template-pipeline.yml
        parameters:
          microservice: 'posts'
          dockerfilePath: 'posts/Dockerfile'
          azureSubscription: 'test-aks-application12'
          imageName: '$(Build.Repository.Name)-$(Build.SourceBranchName)-posts:$(Build.BuildId)'

  - job: BuildUsers
    displayName: 'Build Users Service'
    dependsOn: DetermineService
    condition: and(succeeded(), eq(dependencies.DetermineService.outputs['DetermineService.serviceToBuildOutput'], 'users'))
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: |
          echo "Service to build in BuildUsers: $(serviceToBuild)"
        displayName: 'Debug Service to Build Users'
      - template: template-pipeline.yml
        parameters:
          microservice: 'users'
          dockerfilePath: 'users/Dockerfile'
          azureSubscription: 'test-aks-application12'
          imageName: '$(Build.Repository.Name)-$(Build.SourceBranchName)-users:$(Build.BuildId)'

  - job: BuildUI
    displayName: 'Build UI Service'
    dependsOn: DetermineService
    condition: and(succeeded(), eq(dependencies.DetermineService.outputs['DetermineService.serviceToBuildOutput'], 'ui'))
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: |
          echo "Service to build in BuildUI: $(serviceToBuild)"
        displayName: 'Debug Service to Build UI'
      - template: template-pipeline.yml
        parameters:
          microservice: 'ui'
          dockerfilePath: 'ui/Dockerfile'
          azureSubscription: 'test-aks-application12'
          imageName: '$(Build.Repository.Name)-$(Build.SourceBranchName)-ui:$(Build.BuildId)'
