trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 'ui/*'
      - 'users/*'
      - 'posts/*'
      - 'comments/*'

pool:
  vmImage: ubuntu-latest

variables:
  serviceToBuild: ''  # Default value

jobs:
  - job: DetermineService
    displayName: 'Determine Service to Build'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - checkout: self
        fetchDepth: 0  # Fetch all history to avoid shallow clone issues

      - script: |
          echo "Checking for changes..."
          if [ $(git rev-list --count HEAD) -eq 1 ]; then
              echo "This is the first commit. No previous commit to compare."
              echo "##vso[task.setvariable variable=serviceToBuild;isOutput=true;]none"
          else
              changed_files=$(git diff --name-only HEAD~1 HEAD)
              echo "Changed files: $changed_files"
              # Ensure the paths are matching the correct service directories
              changed_service=$(echo "$changed_files" | grep -E '^(ui|users|posts|comments)/' | cut -d'/' -f1 | uniq | head -n 1)
              if [ -z "$changed_service" ]; then
                  echo "No relevant changes detected."
                  echo "##vso[task.setvariable variable=serviceToBuild;isOutput=true;]none"
              else
                  echo "Detected changes in: $changed_service"
                  echo "##vso[task.setvariable variable=serviceToBuild;isOutput=true;]$changed_service"
              fi
          fi
        displayName: 'Determine Changed Service'

      - script: |
          echo "Service to build set to: $(serviceToBuild)"
          echo "##vso[task.setvariable variable=serviceToBuildFromJob;isOutput=true]$(serviceToBuild)"
          echo "Current build ID: $(Build.BuildId)"
          echo "Current repository: $(Build.Repository.Name)"
          echo "Current branch: $(Build.SourceBranchName)"
          echo "Final serviceToBuild: $(serviceToBuild)"
        displayName: 'Debug Service to Build'