trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 'ui/*'
      - 'users/*'
      - 'posts/*'
      - 'comments/*'

pool:
  vmImage: ubuntu-latest

variables:
  serviceToBuild: ''

jobs:
  - job: DetermineService
    displayName: 'Determine Service to Build'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - checkout: self
        fetchDepth: 0  # Fetch all history to avoid shallow clone issues

      - script: |
          echo "Checking for changes..."
          if [ $(git rev-list --count HEAD) -eq 1 ]; then
              echo "This is the first commit. No previous commit to compare."
              echo "##vso[task.setvariable variable=serviceToBuild]none"
          else
              changed_files=$(git diff --name-only HEAD~1 HEAD)
              echo "Changed files: $changed_files"
              # Ensure the paths are matching the correct service directories
              changed_service=$(echo "$changed_files" | grep -E '^(ui|users|posts|comments)/' | cut -d'/' -f1 | uniq | head -n 1)
              if [ -z "$changed_service" ]; then
                  echo "No relevant changes detected."
                  echo "##vso[task.setvariable variable=serviceToBuild]none"
              else
                  echo "Detected changes in: $changed_service"
                  serviceToBuildTrimmed=$(echo "$changed_service" | xargs)
                  echo "##vso[task.setvariable variable=serviceToBuild;]$serviceToBuildTrimmed"
              fi
          fi
        displayName: 'Determine Changed Service'

      - script: |
          echo "Service to build: $(serviceToBuild)"
        displayName: 'Debug Service to Build'

  - job: BuildComments
    displayName: 'Build Comments Service'
    condition: and(succeeded(), eq(variables['serviceToBuild'], 'comments'))
    steps:
      - script: |
          echo "Service to build: $(serviceToBuild)"
        displayName: 'Debug Service to Build'
      - template: template-pipeline.yml
        parameters:
          microservice: 'comments'
          dockerfilePath: 'comments/Dockerfile'
          azureSubscription: 'test-aks-application12'
          imageName: '$(Build.Repository.Name)-$(Build.SourceBranchName)-comments:$(Build.BuildId)'
