trigger:
- main

pool:
  vmImage: ubuntu-latest

extends:
  template: template-pipeline.yml
  parameters:
    microservice: 'ui'
    dockerfilePath: 'ui/Dockerfile'
    imageTagSuffix: '$(Build.BuildId)'
