trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

steps:
- template: template-pipeline.yml
  parameters:
    microservice: 'users'  # The name of the microservice
    dockerfilePath: 'users/Dockerfile'  # Path to the Dockerfile for users service
    azureSubscription: 'test-aks-application12'  # The Azure subscription name
    imageName: '$(Build.Repository.Name)-$(Build.SourceBranchName)-users:$(Build.BuildId)'  # Image name
